services:
  - type: web
    name: medicine-inventory-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CRON_TIMEZONE
        value: Asia/Kolkata
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        sync: false
